<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_core.php by Valery Votintsev at sources.ru
 */

if(!defined('IN_DISCUZ')) {
	exit('Access Denied');
}

$lang = array
(
	'nextpage'		=> 'Nast.',//'下一页',
	'prevpage'		=> 'Poprz.',//'上一页',
	'pageunit'		=> 'Strony',//'页',
	'total'			=> 'Łącznie',//'共',
	'10k'			=> '10k',//'万',
	'pagejumptip'		=> 'Enter the page number and press Enter for quick jump',//'输入页码，按回车快速跳转',
	'date'	=> array(
		'before'	=> ' temu',//'前',
		'day'		=> 'dni',//'天',
		'yday'		=> 'Wczoraj',//'昨天',
		'byday'		=> 'Przedwczoraj',//'前天',
		'hour'		=> 'godz.',//'小时',
		'half'		=> 'Pół ',//'半',
		'min'		=> 'min.',//'分钟',
		'sec'		=> 's.',//'秒',
		'now'		=> 'przed chwileczką',//'刚刚',
	),
	'yes'			=> 'Tak',//'是',
	'no'			=> 'Nie',//'否',
	'weeks'	=> array(
		1 => 'Poniedziałek',//'周一',
		2 => 'Wtorek',//'周二',
		3 => 'Środa',//'周三',
		4 => 'Czwartek',//'周四',
		5 => 'Piątek',//'周五',
		6 => 'Sobota',//'周六',
		7 => 'Niedziela',//'周日',
	),
	'dot'		=> '. ',//'、',
	'archive'	=> 'Archiwum',//'存档',
	'portal'	=> 'Portal',//'门户',
	'end'		=> 'End',//'末尾',

	'seccode_image_tips'		=> 'Proszę przepisać kod z poniższego obrazka.<br />',//'输入下图中的字符<br />',
	'seccode_image_ani_tips'	=> 'Proszę przepisać kod z animowanego obrazka.<br />',//'请输入下面动画图片中的字符<br />',
	'seccode_sound_tips'		=> 'Enter the characters that you hear<br />',//'输入你听到的字符<br />',
	'secqaa_tips'			=> 'Proszę udzielić odpowiedzi na poniższe pytanie.<br />',//'输入下面问题的答案<br />',

	'fullblankspace'		=> '&nbsp;',//'　',

	'title_goruptype'		=> 'Typ grupy',//'类',
	'title_of'			=> '\'s ',//'的',
	'title_board_message'		=> 'Wiadomość',//'提示信息',
	'title_view_all'		=> 'Wszystko',//'随便看看',
	'title_activity'		=> 'Wydarzenia',//'活动',
	'title_friend_activity'		=> 'Wydarzenia znajomych',//'好友发起的活动',
	'title_my_activity'		=> 'Moje wydarzenia',//'我的活动',
	'title_newest_activity'		=> 'Nowe wydarzenia',//'最新活动',
	'title_top_activity'		=> 'Top wydarzeń',//'热门活动',
	'title_album'			=> 'Albumy',//'相册',
	'title_friend_album'		=> 'Albumy znajomych',//'好友的相册',
	'title_my_album'		=> 'Moje albumy',//'我的相册',
	'title_newest_update_album'	=> 'Ostatnia zaktualizowane albumy',//'最新更新的相册',
	'title_hot_pic_recommend'	=> 'Polecane obrazki',//'热门图片推荐',
	'title_blog'			=> 'Blogi',//'日志',
	'title_friend_blog'		=> 'Blogi znajomych',//'好友的日志',
	'title_my_blog'			=> 'Mój blog',//'我的日志',
	'title_post_new_blog'		=> 'Pisz na blogu',//'发表新日志',
	'title_newest_blog'		=> 'Nowe blogi',//'最新发表的日志',
	'title_recommend_blog'		=> 'Polecane blogi',//'推荐阅读的日志',
	'title_debate'			=> 'Debaty',//'辩论',
	'title_friend_debate'		=> 'Debaty znajomych',//'好友发起的辩论',
	'title_my_debate'		=> 'Moje debaty',//'我的辩论',
	'title_create_new_debate'	=> 'Utwórz debatę',//'发起新辩论',
	'title_my_create_debate'	=> 'Debaty utworzone przeze mnie',//'我发起的辩论',
	'title_my_join_debate'		=> 'I joined Debates',//'我参与的辩论',
	'title_newest_debate'		=> 'New Debates',//'最新辩论',
	'title_top_debate'		=> 'Top Debates',//'热门辩论',
	'title_doing'			=> 'Aktywność',//'记录',
	'title_newest_doing'		=> 'New Doings',//'记录',
	'title_me_friend_doing'		=> 'Friend Doings',//'我和好友的记录',
	'title_doing_view_me'		=> 'My Doings',//'我的记录',
	'title_thread_favorite'		=> 'Ulubione tematy',//'帖子收藏',
	'title_forum_favorite'		=> 'Ulubione fora',//'帖子收藏',
	'title_group_favorite'		=> 'Ulubione grupy &quot;{gorup}&quot;',//'{gorup}收藏',
	'title_blog_favorite'		=> 'Ulubione blogi',//'日志收藏',
	'title_album_favorite'		=> 'Ulubione album',//'相册收藏',
	'title_article_favorite'	=> 'Ulubione artykuły',//'文章收藏',
	'title_all_favorite'		=> 'Wszystkie',//'全部收藏',
	'title_friend_list'		=> 'Lista znajomych',//'好友列表',
//vot	'title_of'			=> 'of',//'的',
	'title_all_poll'		=> 'Wszystkie ankiety',//'随便看看投票',
	'title_we_poll'			=> 'Ankiety znajomych',//'好友发起的投票',
	'title_me_poll'			=> 'Moje ankiety',//'我的投票',
	'title_hot_poll'		=> 'Gorące ankiety',//'热门投票',
	'title_dateline_poll'		=> 'Ostatnie ankiety',//'最新投票',
	'title_all_reward'		=> 'Wszystkie nagrody',//'随便看看悬赏',
	'title_we_reward'		=> 'Nagrody znajomych',//'好友发起的悬赏',
	'title_me_reward'		=> 'Moje nagrody',//'我的悬赏',
	'title_hot_reward'		=> 'Gorące nagrody',//'热门悬赏',
	'title_dateline_reward'		=> 'Ostatnie nagrody',//'最新悬赏',
	'title_share_all'		=> 'Wszystko',//'全部',
	'title_share_link'		=> 'Linki',//'网址',
	'title_share_video'		=> 'Filmy',//'视频',
	'title_share_music'		=> 'Muzyka',//'音乐',
	'title_share_flash'		=> 'Aplikacje flash',
	'title_share_poll'		=> 'Ankiety',//'投票',
	'title_share_pic'		=> 'Zdjęcia',//'图片',
	'title_share_album'		=> 'Albumy',//'相册',
	'title_share_blog'		=> 'Blogi',//'日志',
	'title_share_space'		=> 'Użytkownicy',//'用户',
	'title_share_thread'		=> 'Tematy',//'帖子',
	'title_share_article'		=> 'Artykuły',//'文章',
	'title_share_tag'		=> 'Tagi',//'TAG',
	'title_share'			=> 'Udostępnień',//'分享',
	'title_thread'			=> 'Tematy',//'帖子',
	'title_all_thread'		=> 'Wszystkie tematy',//'随便看看帖子',
	'title_we_thread'		=> 'Tematy znajomych',//'好友发起的帖子',
	'title_me_thread'		=> 'Moje tematy',//'我的帖子',
	'title_hot_thread'		=> 'Gorące tematy',//'热门帖子',
	'title_dateline_thread'		=> 'Ostatnie tematy',//'最新帖子',
	'title_trade'			=> 'Produkty',//'商品',
	'title_all_trade'		=> 'Wszystkie produkty',//'随便看看商品',
	'title_we_trade'		=> 'Produkty znajomych',//'好友出售的商品',
	'title_me_trade'		=> 'Moje produkty',//'我的商品',
	'title_hot_trade'		=> 'Gorące produkty',//'热门商品',
	'title_dateline_trade'		=> 'Ostatnie produkty',//'最新商品',
	'title_tradelog_trade'		=> 'Transakcje',//'交易记录',
	'title_eccredit_trade'		=> 'Points Transactions',//'信用评价',
	'title_credit'			=> 'Punkty',//'积分',
	'title_friend_add'		=> 'Dodaj znajomych',//'添加好友',
	'title_people_might_know'	=> 'Możesz znać',//'可能认识的人',
	'title_friend_request'		=> 'Zaproszenia',//'好友请求',
	'title_search_friend'		=> 'Szukaj',//'查找好友',
	'title_invite_friend'		=> 'Zaproś znajomych',//'邀请好友',
	'title_password_security'	=> 'Ochrona konta',//'密码安全',
	'title_flash_upload'		=> 'Batch Upload',//'批量上传',
	'title_cam_upload'		=> 'Upload standardowy',//'大头贴',
	'title_normal_upload'		=> 'Upload',//'普通上传',
	'title_newthread_post'		=> 'Dodaj nowy temat',//'发表帖子',
	'title_reply_post'		=> 'Odpowiedz w temacie',//'参与/回复主题',
	'title_edit_post'		=> 'Edycja',//'编辑帖子',
	'title_newtrade_post'		=> 'Dodaj produkt',//'发布商品',
	'title_magics_shop'		=> 'Sklep',//'道具商店',
	'title_magics_hot'		=> 'Gorące magie',//'热销道具',
	'title_magics_user'		=> 'Moja magia',//'我的道具',
	'title_magics_log'		=> 'Archiwum magii',//'道具记录',
	'title_medals_list'		=> 'Lista medali',//'勋章',
	'title_setup'			=> 'Ustawienia',//'设置',
	'title_memcp_blog'		=> 'Opublikuj',//'发表日志',
	'title_memcp_upload'		=> 'Wyślij',//'上传',
	'title_memcp_share'		=> 'Udostępnij',//'添加分享',
	'title_memcp_sendmail'		=> 'Mail Alert',//'邮件提醒',
	'title_memcp_privacy'		=> 'Prywatność',//'隐私筛选',
	'title_memcp_avatar'		=> 'Awatar',//'修改头像',
	'title_memcp_profile'		=> 'Osobiste',//'个人资料',
//vot	'title_memcp_sendmail'		=> 'Mail Alert',//'邮件提醒',
	'title_memcp_credit'		=> 'Points',//'积分',
	'title_memcp_friend'		=> 'Znajomi',//'好友',
	'title_memcp_usergroup'		=> 'Grupy',//'用户组',
	'title_memcp_album'		=> 'Albumy',//'编辑相册',
	'title_memcp_poke'		=> 'Greetings',//'打招呼',
	'title_memcp_videophoto'	=> 'Video Authentication',//'视频认证',
	'title_memcp_comment'		=> 'Comments',//'评论',
	'title_memcp_eccredit'		=> 'Points Transactions',//'信用评价',
	'title_memcp_promotion'		=> 'Promuj nas',//'访问推广',
	'title_task'			=> 'Zadania',//'任务',
	'title_login'			=> 'Login',//'登录',
	'title_ranklist_picture'	=> 'Image Ranks',//'图片排行',
	'title_ranklist_member'		=> 'Member Ranks',//'用户排行',
	'title_ranklist_thread'		=> 'Thread Ranks',//'帖子排行',
	'title_ranklist_blog'		=> 'Blog Ranks',//'日志排行',
	'title_ranklist_poll'		=> 'Poll Ranks',//'投票排行',
	'title_ranklist_activity'	=> 'Evant Ranks',//'活动排行',
	'title_ranklist_forum'		=> 'Forum Ranks',//'版块排行',
	'title_ranklist_group'		=> 'Group Ranks',//'群组排行',
	'title_ranklist_app'		=> 'Application Ranking',//'应用排行',
	'title_ranklist_index'		=> 'All Ranks',//'全部排行',
	'title_ranklist_rankname'	=> 'Rank',//'排行榜',
	'title_search'			=> 'Szukaj',//'搜索',
	'title_topic_management'	=> 'Topic Management',//'创建专题',
	'title_portal_management'	=> 'Portal Management',//'门户管理',
	'title_portalblock_management'	=> 'Portal Block Management',//'模块管理',
	'title_block_management'	=> 'Block Management',//'模块管理',
	'title_blockdata_management'	=> 'Block Data Management',//'推送审核',
	'title_index_management'	=> 'Channels Management',//'频道栏目',
	'title_article_management'	=> 'Article Management',//'发布文章',
	'title_category_management'	=> 'Category Management',//'管理文章',

	'title_stats'			=> 'Statystyki',//'站点统计',
	'title_stats_basic'		=> 'Podstawowe statystyki',//'基本概况',
	'title_stats_forumstat'		=> 'Statystyki forum',//'版块统计',
	'title_stats_team'		=> 'Statystyki ekipy',//'管理团队',
	'title_stats_modworks'		=> 'Statystyki moderatorów',//'管理统计',
	'title_stats_memberlist'	=> 'Lista użytkowników',//'会员列表',
	'title_stats_trend'		=> 'Statistics Trends',//'趋势统计',

	'title_memcp_pm'		=> 'Wiadomość',//'发送短消息',
	'title_memcp_domain'		=> 'My space domain',//'我的空间域名',
	'title_userapp'			=> 'Application',//'应用',
	'title_userapp_index_all'	=> 'All Applications',//'大家在玩什么',
	'title_userapp_index_we'	=> 'Friend Applications',//'好友在玩什么',
	'title_userapp_index_me'	=> 'My Applications',//'我在玩的',
	'title_userapp_manage'		=> 'Manage Application &quot;{userapp}&quot;',//'{userapp}管理',

	'title_collection'		=> 'Collection',//'淘帖',
	'title_collection_create'	=> 'Create collection',//'创建淘专辑',
	'title_collection_edit'		=> 'Edit collection',//'编辑淘专辑',
	'title_collection_comment_list'	=> 'Comment list',//'评论列表',
	'title_collection_followers_list'	=> 'Followers',//'订阅用户列表',

	'faq'				=> 'FAQ',//'帮助',
	'search'			=> 'Szukaj',//'搜索',
	'page'				=> 'strona {page}',//'第{page}页',

	'close'				=> 'Zamknij',//'关闭',

//--------------------------------------------------------------------------
// Added by Valery Votintsev

//source/include/misc/misc_security.php
	'attackevasive_1_subject'	=> 'Refresh frequency limit',//'刷新频率限制',
	'attackevasive_1_message'	=> 'You visit the site too fast, less than two seconds! Please wait a little...',//'您访问网站的速度太快，不到两秒钟！请等一下...',
	'attackevasive_2_subject'	=> 'Access throug proxy servers is restricted',//'通过代理服务器的访问是受到限制',
	'attackevasive_2_message'	=> 'Access to the site through a proxy servers is restricted for mow. Please remove your proxy setting configuration, and access to the site directly.',//'通过代理服务器访问网站限制亩。请删除您的代理设置配置，并直接访问该网站。',
	'attackevasive_4_subject'	=> 'Open the page reload',//'打开页面重载',
	'attackevasive_4_message'	=> 'Witamy. Strona zostanie odświeżona, momencik...',//'欢迎的网站，页面重新载入，请稍候...',

// Months Names
	'month_name'	=> array('Miesiąc','Styczeń','Luty','Marzec','Kwiecień','Maj','Czerwiec','Lipiec','Sierpień','Wrzesień','Październik','Listopad','Grudzień'),//array('月','一月','二月','三月','四月','五月','六月','七月','八月','九月','十月','十一月','十二月'),

);

