<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_template.php by Valery Votintsev at sources.ru
 *
 *      This file is automatically generate
 */

$lang = array (
	'activity_about_member'		=> 'Remaining places',//'剩余名额',
	'activity_already'		=> 'Participants number limit is reached already',//'已参加人数',
	'additional'			=> 'Additional',//'附加',
	'debate_opponent'		=> 'Opponent',//'反方',
	'debate_square'			=> 'Square',//'正方',
	'thread_poll'			=> 'Polls',//'投票',
	'credits'			=> 'Kredytów',//'积分',
	'login'				=> 'Login',//'登录',
	'active_email'			=> 'Receive E-mail',//'接收邮箱',
	'active_email_comment'		=> 'Required to receive an invitation code to E-mail Address',//'必填，用来接收邀请码的邮箱地址',
	'apitype_alipay'		=> 'Alipay',
	'apitype_tenpay'		=> 'Tenpay',
	'buy_nums'			=> 'Quantity',
	'confirms'			=> 'Wyślij',//'确定';
	'copycode'			=> 'Copy all to clipboard',//'全部复制到剪贴板',
	'copycode_invite_succeed'	=> 'Invitation code has been copied to the clipboard',//'邀请码已经复制到剪贴板',
	'invitecode_buycode'		=> 'Obtain invitation code',//'获取邀请码',
	'invitecode_email'		=> 'We will also sent invite code to your mailbox <span class="xi1">$order[email]</span> for inspection',//'我们还将邀请码发送到了您填写的邮箱 <span class="xi1">$order[email]</span> 以备查阅',
	'invitecode_expiration'		=> 'Expiration time',//'失效时间',
	'invitecode_succeed_title'	=> 'Congratulations, you have successfully obtained invite code',//'恭喜您，成功获得邀请码',
	'money_unit'			=> 'PLN',//'元',
	'need_money'			=> 'Required to pay',//'需支付',
	'reg_continue'			=> 'Continue Registration',//'继续注册',
	'trade_type'			=> 'Payment method',//'付款方式',
	'e_fontoptions'			=> '"Arial", "Verdana", "Tahoma", "Times New Roman", "Impact", "Trebuchet MS"',//'"仿宋_GB2312", "黑体", "楷体_GB2312", "宋体", "新宋体", "微软雅黑", "Trebuchet MS", "Tahoma", "Arial", "Impact", "Verdana", "Times New Roman"',
	'editor_increase'		=> 'Powiększ',//'加大编辑框',
	'editor_narrow'			=> 'Zmniejsz',//'缩小编辑框',
	'post_autosave_restore'		=> 'Przywróć',//'恢复数据',
	'post_check_length'		=> 'Ilość znaków',//'字数检查',
	'post_savedata'			=> 'Zapisz',//'保存数据',
	'post_topicreset'		=> 'Wyczyść treść',//'清除内容',
	'all'				=> 'All',//'全部',
	'faq'				=> 'FAQ',//'帮助',
	'faq_search_nomatch'		=> 'Sorry, no results found',//'对不起,没有找到匹配结果',
	'homepage'			=> 'Home',//'首页',
	'keyword_faq'			=> 'Keyword &quot;<span class="xi1">$keyword</span>&quot; Help',//'关键字为“<span class="xi1">$keyword</span>”Help',
	'open'				=> 'Open',//'展开',
	'search'			=> 'Szukaj',//'搜索',
	'close'				=> 'Close',//'关闭',
	'focus_hottopics'		=> 'Hot Topics',//'站长推荐',
	'focus_show'			=> 'View',//'查看',
	'footer_next'			=> 'Next post',//'下一条',
	'footer_previous'		=> 'Previous post',//'上一条',
	'login_invisible_mode'		=> 'Ukryty',//'隐身',
	'login_normal_mode'		=> 'Online',//'在线',
	'scrolltop'			=> 'To Top',//'回顶部',
	'thread_groupupgrade'		=> 'Do następnego poziomu brakuje',//'距离下一级还需',
	'time_now'			=> '{$_G[timenow][time]} GMT{$_G[timenow][offset]}',
	'activation'			=> 'Activation',//'激活',
	'admincp'			=> 'Administracja',//'管理中心',
/*vot*/	'changestyle'			=> '',//'Change Style:',//'切换风格',
	'cloudcp'			=> 'CloudCP',//'云平台',
	'default'			=> 'Default',//'默认',
	'forum_manager'			=> 'Panel Moderatora:',//'{$_G[setting][navs][2][navname]}管理',
	'go_to_mobile'			=> 'To the mobile version',//'进入手机版',
	'header_diy_mode_adv'		=> 'Tryb zaawansowany',//'高级模式',
	'header_diy_mode_simple'	=> 'Tryb prosty',//'简洁模式',
	'header_qq_login_user'		=> 'QQ logged user',//'QQ 登录用户',
	'login_switch_invisible_mode'	=> 'Zmień status online',//'切换在线状态',
	'logout'			=> 'Wyloguj',//'退出',
	'my_nav'			=> 'Nawigacja',//'我的中心',
	'my_nav_login'			=> 'Proszę <a href="javascript:;" class="xi2" onclick="lsSubmit()"><strong>zaloguj</strong></a> się, aby móc skorzystać z nawigacji. <br />Nie masz konta? <a href="member.php?mod={$_G[setting][regname]}" class="xi2 xw1">Zarejestruj</a> się!',//'请 <a href="javascript:;" class="xi2" onclick="lsSubmit()"><strong>登录</strong></a> 后使用快捷导航<br />没有帐号？<a href="member.php?mod={$_G[setting][regname]}" class="xi2 xw1">注册</a>',
	'open_diy'			=> 'Layout Panel',//'打开 DIY 面板',
	'pm_center'			=> 'Prywatne wiadomości',//'短消息',
	'portal_block_manage'		=> 'Block Management',//'模块管理',
	'portal_manage'			=> 'Portal management',//'门户管理',
	'remind'			=> 'Powiadomienia',//'提醒',
	'setup'				=> 'Profil',//'设置',
	'switch_narrow'			=> 'Narrow screen',//'切换到窄版',
	'switch_wide'			=> 'Wide screen',//'切换到宽版',
/*!*/	'switch_blind'			=> 'Enable Auxiliary Access',//'开启辅助访问',
	'task_doing'			=> 'W toku',//'进行中的任务',
	'to_be_continue'		=> 'Continue to access the desktop computer version',//'继续访问电脑版',
	'usergroup'			=> 'Status',//'用户组',
	'visit_my_space'		=> 'Visit My Space',//'访问我的空间',
	'your_mobile_browser'		=> 'Please select ',//'请选择 ',
	'e_redo'			=> 'Przywróć',//'重做',
	'e_undo'			=> 'Cofnij',//'撤销',
	'header_add_frame'		=> 'Dodaj okno',//'添加框架',
	'header_add_module'		=> 'Dodaj blok',//'添加模块',
	'header_clearall'		=> 'Wyczyść wszystko',//'清空',
	'header_clearall_desc'		=> 'Clear all layout data of current page',//'清空页面上所在DIY数据',
	'header_diy'			=> 'Customize',//'自定义',
	'header_diy_backup_tip'		=> 'W każdej chwili możesz utworzyć kopię zapasową swoich szablonów.',//'你可以通过导出进行模板备份',
	'header_diy_i_know'		=> 'Rozumiem',//'我知道了',
	'header_diy_sample_mode'	=> 'Używasz <strong>Trybu prostego</strong>. Możesz aktualizować bloki, modyfikować ich zawartość oraz dane. Aby móc korzystać z pełnej kontroli przejdź do <a href="javascript:;" onclick="spaceDiy.init();" class="xw1 xi2">Trybu zaawansowanego</a>.',//'当前为<strong>简洁模式</strong>，您可以更新模块，修改模块属性和数据，要使用完整的拖拽功能，<a href="javascript:;" onclick="spaceDiy.init();" class="xw1 xi2">请点击进入高级模式</a>',
	'header_export'			=> 'Eksport',//'导出',
	'header_export_desc'		=> 'Export current page layout',//'导出当前页面中所有DIY数据',
	'header_frame'			=> 'Okienka',//'框架',
	'header_import'			=> 'Import',//'导入',
	'header_import_desc'		=> 'Import layout data into the current page',//'将DIY数据导入到当前页面',
	'header_module'			=> 'Moduły',//'模块',
	'header_more_actions'		=> 'More actions',//'更多操作',
	'header_perview'		=> 'Preview',//'预览',
	'header_perview_desc'		=> 'Preview customized layout',//'预览DIY的效果',
	'header_restore_backup'		=> 'Przywróć',//'恢复备份',
	'header_restore_backup_desc'	=> 'Restore layout from backup',//'恢复备份',
	'header_start'			=> 'Start',//'开始',
	'header_update'			=> 'Update',//'更新',
	'header_update_desc'		=> 'Update all blocks data in the current page',//'更新当前页面所有模块的数据',
	'save'				=> 'Zapisz',//'保存',
	'style'				=> 'Style',//'风格',
	'find'				=> 'Find',//'查找',
	'invite'			=> 'Invite',//'邀请',
	'invite_all_friend'		=> 'Wszyscy',//'全部好友',
	'invite_friend'			=> 'Zaproś',//'邀请好友',
	'invite_my_follow'		=> 'I am follow',//'我关注的',
	'invite_orderby_friend'		=> 'Kategoria znajomych',//'按好友分组查找',
	'invite_orderby_name'		=> 'Nazwa znajomego',//'按好友用户名查找',
	'invite_send'			=> 'Wyślij zaproszenie',//'发送邀请',
	'invite_still_choose'		=> 'Możesz wybrać ',//'还能选择',
	'selected'			=> 'Wybranych',//'已选',
	'unit'				=> ' na raz',//'个',
	'unselected'			=> 'Możliwych',//'未选',
	'imgcropper'			=> 'Crop Image',//'裁切图片',
	'imgcropper_crop'		=> 'Crop',//'裁切',
	'preview_footertext'		=> 'Copyright and Footer info',//'版权及页脚信息',
	'preview_highlightlink'		=> 'Highlight link',//'高亮链接',
	'preview_lighttext'		=> 'HighLight Text',//'浅色文字',
	'preview_link'			=> 'Link Text',//'链接文字',
	'preview_midtext'		=> 'Medium text',//'中等文本',
	'preview_msg'			=> '<a href="javascript:;" class="xi2">Crossday Discuz! Board</a> Community System (Abbreviation <strong class="xw1 xi1">Discuz!</strong>) is a PHP and MySQL system using a variety of database technologies and other high-level communication solutions.',//'<a href="javascript:;" class="lit">Crossday Discuz! Board</a> 社区系统（简称 <stong class="xw1 xi1">Discuz!</stong>）是一个采用 PHP 和 MySQL 等其他多种数据库构建的高效建站解决方案。',
	'preview_smalltext'		=> 'Small Font',//'SMALL FONT',
	'preview_text'			=> 'Plain text',//'普通文本',
	'preview_threadtext'		=> 'Preview thread',//'主题列表字体',
	'table_header'			=> 'Header',//'表头',
	'album'				=> 'Albumy',//'相册',
	'article'			=> 'Articles',//'文章',
	'blog'				=> 'Blogi',//'日志',
	'enter_content'			=> 'Wprowadź szukane wyrażenia',//'请输入搜索内容',
	'hot_search'			=> 'Polecane',//'热搜',
	'search_this_forum'		=> 'To forum',//'本版块',
	'thread'			=> 'Tematy',//'帖子',
	'users'				=> 'Użytkownicy',//'用户',
	'input_message1'		=> 'Do wykorzystania',//'还可输入',
	'input_message2'		=> 'znaków',//'个字符',
	'report'			=> 'Raport',//'举报',
	'report_reason'			=> 'Powód zgłoszenia',//'举报理由',
	'seccode'			=> 'Kod',//'验证码',
	'seccode_change'		=> 'Odśwież',//'换一个',
	'secqaa'			=> 'Pytanie',//'验证问答',
	'at_friend'			=> '@user',//'@朋友',
	'e_at'				=> '@user',//'@朋友',
	'e_bold'			=> 'Pogrubienie',//'文字加粗',
	'e_code'			=> 'Code',//'代码',
	'e_forecolor'			=> 'Kolor tekstu',//'设置文字颜色',
	'e_image'			=> 'Zdjęcie',//'图片',
	'e_quote'			=> 'Cytat',//'引用',
	'e_url'				=> 'Link',//'添加链接',
	'attach_forward'		=> 'If the download is not started in {$refreshsecond} seconds, please click here',//'如果 {$refreshsecond} 秒后下载仍未开始,请点击此链接',
	'board_message'			=> 'Powiadomienie',//'提示信息',
	'cancel'			=> 'Cancel',//'取消',
	'message_closetime'		=> ' sek. do zamknięcia powiadomienia.',//'秒后窗口关闭',
	'message_forward'		=> 'Kliknij tutaj, jeśli przeglądarka nie przekieruje Cię automatycznie',//'如果您的浏览器没有自动跳转,请点击此链接',
	'message_go_back'		=> '[Kliknij tutaj, aby powrócić do poprzedniej strony]',//'[ 点击这里返回上一页 ]',
	'message_locationtime'		=> 'Seconds after the page jump',//'秒后页面跳转',
	'basic_situation'		=> 'Ogólne',//'基本概况',
	'forum_stat'			=> 'Statystyki',//'版块统计',
	'manage_team'			=> 'Ekipa',//'管理团队',
	'member_list'			=> 'Użytkownicy',//'会员列表',
	'mod_works'			=> 'Moderatorzy',//'管理统计',
	'stats'				=> 'Statystyki',//'站点统计',
	'trend'				=> 'Wykresy',//'趋势统计',
	'app_add'			=> 'Add application',
	'app_management'		=> 'Manage application',
	'submit'			=> 'Wyślij',//'提交',
	'e_attach_del'			=> 'Usuń',//'删除',
	'e_attach_mediacode'		=> 'Add media player code for attachment',//'添加附件媒体播放代码',
	'e_attach_url'			=> 'Add Attachment URL',//'添加附件地址',
	'readperm'			=> 'Read Permission',//'阅读权限',
	'update'			=> 'Update',//'更新',
	'delete'			=> 'Usuń',//'删除',
	'none_newthread'		=> 'Brak nowych treści.',//'暂无新回复主题',
	'author'			=> 'Autor',//'作者',
	'username'			=> 'Użytkownik',//'用户名',
	'anonymous'			=> 'Anonim',//'匿名',
	'edit'				=> 'Edytuj',//'编辑',
	'thread_activity'		=> 'Events',//'活动',
	'thread_debate'			=> 'Debates',//'辩论',
	'thread_reward'			=> 'Rewards',//'悬赏',
	'thread_trade'			=> 'Sales',//'商品',
	'more'				=> 'Więcej',//'更多',
	'publish'			=> 'Publish',//'[+]',//'发布',
	'guest'				=> 'Gość',
	'upload'			=> 'Upload',//'上传',
	'e_attach_insert'		=> 'Click a filename to insert into the content',//'点击文件名添加到帖子内容中',
	'e_attach_inserturl'		=> ', &quot;attach://&quot; at the beginning of the attachment address support the download for anyone, please add carefully.',//', "attach://" 开头的附件地址支持任何人下载请谨慎添加',
	'e_img_albumlist'		=> 'Album Images',//'相册图片',
	'e_img_attach'			=> 'Upload images',//'上传图片',
	'e_img_height'			=> 'Height (optional)',//'高(可选)',
	'e_img_insertphoto'		=> 'Click an image for insert into the content',//'点击图片添加到帖子内容中',
	'e_img_inserturl'		=> 'Please enter the image URL',//'请输入图片地址',
	'e_img_width'			=> 'Width (optional)',//'宽(可选)',
	'e_img_www'			=> 'Image link',//'网络图片',
	'target_blank'			=> 'Otwórz w nowym oknie',//'新窗口打开',
	'return'			=> 'Return',//'返回',
	'discuzcode'			=> 'BB-Code',//'Discuz 代码',
	'member'			=> 'Member',//'会员',
	'panel_login'			=> 'Manager Login',//'登录管理面板',
	'panel_login_password'		=> 'Hasło',//'密码',
	'panel_login_username'		=> 'Użytkownik',//'用户名',
	'panel_notice_login'		=> 'When you enter the control panel for a first time (or after a long time idle), you must enter your password. If you have entered wrong password more than 5 times, the control panel will be locked for 15 minutes.',//'首次进入管理面板或空闲时间过长, 你输入密码才能进入。如果密码输入错误超过 5 次,管理面板将会锁定 15 分钟。',
	'select_all'			=> 'Select All',//'全选',
	'e_at_title'			=> 'Wprowadź odnośnik do profilu użytkownika',//'@好友和关注的人',
	'e_attach'			=> 'Attachment',//'附件',
	'e_attach_title'		=> 'Add Attachment',//'添加附件',
	'e_audio'			=> 'Audio',//'音乐',
	'e_audio_title'			=> 'Add Audio',//'添加音乐',
	'e_autotypeset'			=> 'Type Auto-Set',//'自动排版',
	'e_center'			=> 'Align Center',//'居中',
	'e_code_title'			=> 'Add Code',//'添加代码文字',
	'e_downremoteimg'		=> 'Download Image',//'下载图片',
	'e_downremoteimg_title'		=> 'Download remote images',//'下载远程图片',
	'e_flash'			=> 'Flash',
	'e_flash_title'			=> 'Dodaj flash',//'添加 Flash',
	'e_font'			=> 'Czcionka',//'字体',
	'e_fontname'			=> 'Nazwa czcionki',//'设置字体',
	'e_fontsize'			=> 'Rozmiar czcionki',//'设置文字大小',
	'e_free'			=> 'Add Free Info',//'添加免费信息',
	'e_hide'			=> 'Ukryta treść',//'添加隐藏内容',
	'e_hr_title'			=> 'Pozioma linia',//'分隔线',
	'e_image_title'			=> 'Dodaj zdjęcie',//'添加图片',
	'e_italic'			=> 'Kursywa',//'文字斜体',
	'e_left'			=> 'Align Left',//'居左',
	'e_orderedlist'			=> 'Lista uporządkowana (numerowana)',//'排序的列表',
	'e_pasteword'			=> 'Paste from Word',//'Word 粘贴',
	'e_pasteword_title'		=> 'Wklej zawartość z aplikacji Word',//'从 Word 粘贴内容',
	'e_quote_title'			=> 'Add Quote',//'添加引用文字',
	'e_removeformat'		=> 'Usuń formatowanie',//'清除文本格式',
	'e_right'			=> 'Align Right',//'居右',
	'e_size'			=> 'Size',//'大小',
	'e_smilies'			=> 'Smiles',//'表情',
	'e_smilies_title'		=> 'Add Smiles',//'添加表情',
	'e_table'			=> 'Table',//'添加表格',
	'e_underline'			=> 'Underline',//'文字加下划线',
	'e_unlink'			=> 'Usuń link',//'移除链接',
	'e_unorderedlist'		=> 'Lista nieuporządkowana',//'未排序列表',
	'e_video'			=> 'Video',//'视频',
	'e_video_title'			=> 'Add Video',//'添加视频',
	'smilies'			=> 'Smiles',//'表情',
	'uid'				=> 'UID',
	'recommend'			=> 'Recommend block',//'模块推送',
	'trade'				=> 'Sales',//'商品',
	'manage'			=> 'Wybierz',//'管理',
	'not_enough'			=> 'Insufficient',//'不足',
	'moderate_need'			=> 'Pending',//'待审核',
	'portal'			=> 'Portal',//'门户',
	'reward_answer'			=> 'I answered',//'我来回答',
	'favorite'			=> 'Ulubione',//'收藏',
	'choose_please'			=> 'Please select',//'请选择',
	'create'			=> 'Create',//'创建',
	'finished'			=> 'Finished',//'完成',
	'ignore_all'			=> 'Ignore all',//'忽略全部',
	'pass_all'			=> 'Approve all',//'全部通过',
	'create_on'			=> 'Created at',//'创建于',
	'activity'			=> 'Events',//'活动',
	'debate'			=> 'Debates',//'辩论',
	'poll'				=> 'Polls',//'投票',
	'reward'			=> 'Rewards',//'悬赏',
	'add'				=> 'Add',//'添加',
	'blockdata_recommend'		=> 'Recommend block',//'模块推送',
	'share'				=> 'Udostępnień',//'分享',
	'article_push'			=> 'Generate Article',//'生成文章',
	'doing'				=> 'Aktywność',//'记录',
	'friends'			=> 'Znajomi',//'好友',
	'online_member'			=> 'Online members',//'在线成员',
	'my_space'			=> 'My Space',//'我的中心',
	'magic'				=> 'Magia',//'道具',
	'medals'			=> 'Medale',//'勋章',
	'task'				=> 'Zadania',//'任务',
	'notice'			=> 'Notice',//'提醒',
	'you'				=> 'You',//'您',
	'group_expiry_type_ext'		=> 'Extended user group',//'扩展用户组',
	'task_done'			=> 'Ukończone',//'已完成的任务',
	'task_failed'			=> 'Popsute',//'失败的任务',
	'task_new'			=> 'Nowe',//'新任务',
	'task_admins'			=> 'Administrators',//'管理人员',
	'task_applicants'		=> 'This task completed $task[applicants] members',//'已有 $task[applicants] 位会员参与此任务',
	'task_applies_full'		=> 'Task limit is reached',//'人数已满',
	'task_apply_condition'		=> 'Task conditions',//'申请此任务所需条件',
	'task_applyagain'		=> 'You can apply again after',//'后可以再次申请',
	'task_applyagain_now'		=> 'Now you can re-apply',//'现在可以再次申请',
	'task_complete'			=> 'Completed',//'已完成',
	'task_complete_condition'	=> 'Conditions to complete the task',//'完成此任务所需条件',
	'task_complete_on'		=> 'Completed at ',//'完成于',
	'task_detail'			=> 'Task Details',//'任务详情',
	'task_endtime'			=> 'The task end time is $task[endtime], you can not apply it after expiration',//'当前任务下线时间为 $task[endtime],过期后您将不能申请此任务',
	'task_general_users'		=> 'Ordinary members',//'普通会员',
	'task_group_nopermission'	=> 'Your user group can not apply this task',//'您所在的用户组无法申请此任务',
	'task_lose_on'			=> 'Failed at ',//'失败于',
	'task_numlimit'			=> 'Members limit',//'人次上限',
	'task_period_day'		=> 'You can apply the task every $task[period] day(s)',//'每 $task[period] 天允许申请一次',
	'task_period_hour'		=> 'You can apply the task every $task[period] hour(s)',//'每隔 $task[period] 小时允许申请一次',
	'task_period_month'		=> 'You can apply the task every $task[period] month(s)',//'每月 $task[period] 日允许申请一次',
	'task_period_week'		=> 'You can apply the task every $periodweek week(s)',//'每周 $periodweek 允许申请一次',
	'task_reapply'			=> 'Can re-applied after',//'后可以重新申请',
	'task_reapply_now'		=> 'You can re-apply now',//'现在可以重新申请',
	'task_relatedtask'		=> 'Must complete assigned tasks',//'必须完成指定任务',
	'task_reward'			=> 'Task Reward',//'奖励',
	'task_applies'			=> 'Applies',//'人气',
	'task_nodoing'			=> 'No ongoing tasks, please apply a new task!',//'暂无进行中的任务,请到新任务中申请！',
	'task_nonew'			=> 'No new tasks. But you can complete periodic tasks again later, please pay attention!',//'暂无新任务,周期性任务完成后可以再次申请,敬请关注！',
	'password_security'		=> 'Password & Security',//'密码安全',
	'increase'			=> 'Increase',//'增加',
	'friend_top'			=> 'Friend Top List',//'排行榜',
	'connect_config_newpassword_comment'	=> 'You are currently use a QQ account was bind to the site. Here you can set up individual password, Only set up an independent password site to fill in the password so the corresponding function can use it',//'你目前使用的是QQ帐号绑定本站，你可以在这里设置独立密码，只有设置了独立密码后本站需要填写密码的相应功能才可使用',
	'email'				=> 'Email',
	'security_question'		=> 'Pytanie zabezpieczające (Zignoruj, jeśli nie używasz)',//'安全提问(未设置请忽略)',
	'security_question_0'		=> 'Security Question',//'安全提问',
	'security_question_1'		=> 'Nazwisko panieńskie matki',//'母亲的名字',
	'security_question_2'		=> 'Imię dziadka',//'爷爷的名字',
	'security_question_3'		=> 'Miejsce urodzenia ojca',//'父亲出生的城市',
	'security_question_4'		=> 'Nazwisko pierwszego wychowawcy',//'你其中一位老师的名字',
	'security_question_5'		=> 'Model użytkującego komputera',//'你个人计算机的型号',
	'security_question_6'		=> 'Nazwa ulubionej restauracji',//'你最喜欢的餐馆名称',
	'security_question_7'		=> 'Ostatnie 4 znaki tablicy rejestracyjnej pojazdu',//'驾驶执照最后四位数字',
	'group_expiry_time'		=> 'Expiration Time',//'到期时间',
	'login_id'			=> 'ID konta',//'帐号',
	'login_password'		=> 'Hasło',//'密码',
	'login_permanent'		=> 'Zapamiętaj mnie',//'记住我的登录状态',
	'security_a'			=> 'Odpowiedź',//'答案',
	'security_q'			=> 'Pytanie zabezpieczające',//'安全提问',
	'forgotpw'			=> 'Zapomniałeś hasła?',//'找回密码',
	'image'				=> 'Images',//'图片',
	'remote'			=> 'Remote',//'远程',
	'credit_ranking'		=> 'Top Points',//'积分排行',
	'auction_ranking'		=> 'Top bidding',//'竞价排行',
	'close_ranking_note'		=> 'Administrator has closed the bidding. For the time you can not continue the Ranking',//'管理员已关闭竞价,暂时无法继续上榜',
	'credit_is_not_number'		=> 'Entered value {$extcredits[$creditid][title]} is not valid',//'你所填写的{$extcredits[$creditid][title]}不是一个合法数值',
	'credit_title_error'		=> 'Entered value {$extcredits[$creditid][title]} can not be less than 1',//'你所填写的{$extcredits[$creditid][title]}不能小于1',
	'credit_title_message'		=> 'Your current {$extcredits[$creditid][title]} is: "+maxCredit+", please fill in a value less than this number',//'你的当前{$extcredits[$creditid][title]}为: "+maxCredit+",请填写一个小于该值的数字',
	'current_ranking'		=> 'Current position',//'当前排名',
	'friend_need_help'		=> 'Help to this Friend',//'要帮助的好友',
	'friend_num_ranking'		=> 'Add Ranking amount',//'好友数排行',
	'friend_top_note'		=> 'Rank description',//'排行榜公告',
	'handsel'			=> 'Present',//'赠送',
	'handsel_bid'			=> 'Present bids',//'赠送竞价',
	'help_friend_in_top'		=> 'Helping friends to Ranking',//'帮助好友来上榜',
	'i_ranking'			=> 'Rank to myself',//'我也要上榜',
	'increase_bid'			=> 'Increase bid',//'增加竞价',
	'make_persistent_efforts'	=> 'Make persistent efforts',//'再接再厉',
	'max_char_ranking'		=> 'up to 50 characters, will appear in the top list',//'最多50个汉字,会显示在榜单中',
	'my_ranking_declaration'	=> 'Rank description',//'我的上榜宣言',
	'not_exceed'			=> 'Not more than you have ',//'不要超过自己的',
	'ranking_message_0'		=> 'You have not yet bid rank. Ranking yourself will greatly enhance the visibility of your home space.',//'你现在还没有上榜。让自己上榜吧,这会大大提升你的主页曝光率。',
	'ranking_message_1'		=> 'Bid {$extcredits[$creditid][title]} more,  the higher will be your home page exposure;',//'竞价{$extcredits[$creditid][title]}越多,竞价排名越靠前,你的主页曝光率也会越高；',
	'ranking_message_2'		=> 'Ranking the user is another effective browsing time, its bid {$extcredits[$creditid][title]} will be reduced by a (malicious refresh access is not deductible).',//'上榜用户的主页被别人有效浏览一次,其竞价{$extcredits[$creditid][title]}将减少1个(恶意刷新访问不扣减)。',
	'self_current_credit'		=> 'Your current points',//'你当前的积分',
	'self_current_friend_num'	=> 'Current number of your friends',//'你当前的好友数',
	'top_100_update'		=> 'The following is the top 100 rank list. The data data updated every $cache_time minutes.',//'下面列出的为排行前100名, 数据每 $cache_time 分钟更新一次。',
	'your_current_bid'		=> 'Your current bid',//'自己当前的竞价',
	'top_orderby_blogs'		=> 'by number of blogs',//'按日志总数',
	'top_orderby_credits'		=> 'by number of points',//'按积分总数',
	'top_orderby_posts'		=> 'by number of posts',//'按发帖总数',
	'top_orderby_uid'		=> 'by registration time',//'按注册时间',
	'upload_pic'			=> 'Dodaj zdjęcie',//'上传图片',
	'aim_album'			=> 'Upload to album:',//'上传到:',
	'default_album'			=> 'Album domyślny',//'默认相册',
	'create_new_album'		=> 'Utwórz nowy album',//'创建新相册',
	'input_album_name'		=> 'Please enter the album name',//'请输入相册名称',
	'click_pic_to_editor'		=> 'Click the image to insert into the content',//'点击图片添加到编辑器内容中',
	'select_album'			=> 'Wybierz album',//'选择相册',
	'upload_attach'			=> 'Upload attachment',//'上传附件',
	'filename'			=> 'File Name',//'文件名',
	'file_size'			=> 'File Size',//'文件大小',
	'click_filename_to_article'	=> 'Click the file name for add attachment into the article',//'点击文件名将附件添加到文章中',
	'connect_fill_profile_to_visit'	=> 'Please<br /><a class="xi2" href="member.php?mod=connect"><strong>Provide the account information</strong></a> or <a href="member.php?mod=connect&ac=bind" class="xi2 xw1"><strong>Bind existing account</strong></a><br />for use the Quick Navigation',//'请先<br /><a class="xi2" href="member.php?mod=connect"><strong>完善帐号信息</strong></a> 或 <a href="member.php?mod=connect&ac=bind" class="xi2 xw1"><strong>绑定已有帐号</strong></a><br />后使用快捷导航',

//---------------------------
// Added by Valery Votintsev

	'follow_view_follow'		=> 'I follow',//'我关注的',
	'follow_stop'			=> 'Stop follow',//'不收听',
	'follow_start'			=> 'Follow',//'收听TA',

	'e_full_screen'			=> 'Pełen ekran',//'全屏',
	'e_restore_size'		=> 'Przywróć rozmiar',//'恢复',
	'e_simple'			=> 'Tryb uproszczony',//'常用',
	'e_advanced'			=> 'Tryb rozszerzony',//'高级',

//static/space/t1/style.css
	'default_style'	=> 'Default style',//'[name]默认风格[/name]',

//---------------------------
//static/space/t2/style.css
	'nature'	=> 'Nature',//'[name]自然[/name]',

//---------------------------
//static/space/t3/style.css
	'sky'		=> 'Sky',//'[name]天空[/name]',

//---------------------------
//static/space/t4/style.css
	'cat'		=> 'Cat',//'[name]猫猫[/name]',

//---------------------------
//static/space/t5/style.css
	'courtyard'	=> 'Courtyard',//'[name]庭院[/name]',

//---------------------------
//static/space/t6/style.css
	'green_wall'	=> 'Green Wall',//'[name]绿墙[/name]',

//---------------------------
//static/space/t7/style.css
	'cowboy'	=> 'Cowboy',//'[name]牛仔[/name]',

//---------------------------
//static/space/t8/style.css
	'christmas'	=> 'Christmas',//'[name]圣诞[/name]',

//---------------------------
//static/topic/t1/style.css
	'default_skin'	=> 'Default Skin',//'[name]默认皮肤[/name]',

//---------------------------
//static/topic/t2/style.css
	'skin_2'	=> 'Skin 2',//'[name]皮肤2[/name]',

//---------------------------
//Change Language
	'change_language'	=> '',//'Change language:',
	'change_language_title'	=> 'Zmień język',
	'changestyle_title'	=> 'Zmień styl',//'切换风格',

//vot:
	'new'		=> 'Nowe',//'全新',

	'register'	=> 'Zarejestruj się',//'注册',

	'or'		=> 'or',//'或者',

// Google Maps
	'e_map'		=> 'Map',//'地图',
	'e_map_insert'	=> 'Wprowadź lokalizację dzięki Google map',//'插入google地图',
	'e_map_address'	=> 'Wyszukaj lokalizację: ',//'地址： ',

);

