<?php

/**
 *      [Discuz!] (C)2001-2099 Comsenz Inc.
 *      This is NOT a freeware, use is subject to license terms
 *
 *      $Id: lang_template.php by Valery Votintsev, codersclub.org
 *
 *      This file is automatically generate
 */

$lang = array (
	'no_simplemobiletype'		=> 'Standardowa edycja',//'标准版',
	'nomobiletype'			=> 'Pełna wersja forum',//'电脑版',
	'simplemobiletype'		=> 'Wersja mobile',//'精简版',
	'favorite'			=> 'Ulubione',//'收藏',
	'my_posts'			=> 'Moje posty',//'我的帖子',
	'new_pm'			=> 'Nowa wiadomość',//'新短消息',
	'waptitle'			=> 'Mobile',//'手机版',
	'login_mobile'			=> 'Sprawdź - {$_G[setting][bbname]} mobile',//'现在就登录 - {$_G[setting][bbname]} 手机版',
	'login_mobile_join'		=> 'Już teraz możesz przeglądać forum w wersji mobile.',//'立即使用手机访问，获得极速移动体验',
	'mobile_favorite'		=> 'Szybki dostęp do ulubionych',//'快速收藏',
	'mobile_favorite_comment'	=> 'Uzyskaj szybki dostęp do ulubionych tematów na forum poprzez swój telefon, gdziekolwiek jesteś.',//'您可以通过手机快速访问论坛版块及管理收藏夹，随时随地访问自己最爱的内容',
	'mobile_other_1'		=> 'Zachowaj minimalne zużycie transferu dzięki specjalnemu formatowaniu. Strony wczytują się piorunująco szybko!',//'节省流量与获得优质手机体验并存',
	'mobile_pm'			=> 'Utrzymaj kontakt ze znajomymi poprzez prywatne wiadomości bądź chat.',//'站内短信实时收发，与短信另一端的朋友进行单人或多人聊天',
	'mobile_viewthread'		=> 'Weź udział w dyskusji',//'看帖及回帖更快速',
	'mobile_viewthread_comment'	=> 'Przeglądaj i udzielaj się w dyskusjach łącznie z użytkownikami forum.',//'通过手机版，可以快速的访问您需要阅读的主题，并可以快速的发布新帖及回复',
	'continue'			=> 'Kontynuuj',//'继续访问',
	'goback'			=> 'Powrót',//'返回上一页',
	'message_forward_mobile'	=> 'click on this link to jump',//'点击此链接进行跳转',
	'favorite_delete'		=> 'Usuń z ulubionych',//'取消收藏',
	'index_members'			=> 'Użytkowników ',//'会员',
	'index_today'			=> 'Dziś ',//'今日',
	'my_favorites_forums'		=> 'Ulubione fora',//'我收藏的版块',
	'online'			=> 'Online',//'在线',
	'sourceimagesize'		=> 'Oryginalny rozmiar',//'原图尺寸',
	'forum_posts'			=> 'Odpowiedzi',//'回',
	'group'				=> 'Grupa',//'群',
	'post_newthreaddebate'		=> 'Nowa debata',//'发辩论',
	'post_newthreadpoll'		=> 'Nowa ankieta',//'发投票',
	'post_newthreadreward'		=> 'Nowa nagroda',//'发悬赏',
	'send_threads'			=> 'Post',//'发帖',
	'thread_digest'			=> 'Wykop',//'精',
	'thread_recommend'		=> 'Polecane',//'荐',
	'thread_sticky'			=> 'Przyklejony',//'顶',
	'threadsort'			=> 'Kategoria tematu',//'分类信息',
	'threadtype'			=> 'Typ tematu',//'主题分类',
	'viewnewthread'			=> 'Nowy temat',//'新帖排序',
	'admin_threadtopicadmin_error'	=> 'Mobilna wersja strony nie wspiera wszystkich możliwych operacji.',//'手机版不支持复杂管理操作',
	'expiry'			=> 'Time <span class="xg2">(0 for permanent / 1 is 1 day)</span>',//'期限<span class="xg2">(0为永久/1为1天)</span>',
	'mod_message_goto_admincp'	=> 'Skorzystaj z przeglądarki internetowej komputera by uzyskać dostęp do zaawansowanych funkcji.',//'需要您使用电脑浏览器进入后台进行高级功能操作',
	'result'			=> 'Wyniki wyszukiwarki',//'查找结果',
	'join_thread'			=> 'Dołącz do tematu',//'回复',
	'required'			=> 'Wymagane',//'必填',
	'send_special_activity_error'	=> 'Mobile does not support <strong>activity</strong> adding, please click on the top post for choose other way',//'手机版不支持<strong>活动</strong>发布，请点击上方发帖选择其他方式',
	'send_special_trade_error'	=> 'Wersja mobilna nie wspiera dodawanie <strong>produktów</strong>, proszę wybrać inny typ tematu.',//'手机版不支持<strong>商品</strong>发布，请点击上方发帖选择其他方式',
	'threadsort_error'		=> 'For publish category info, use the computer version',//'发布分类信息请使用电脑版',
	'threadsort_calendar'		=> 'Format daty: 2010-12-31',//'日期格式：2010-12-01',
	'post_poll_options'		=> 'Ustawienia ankiety',//'投票选项',
	'admin_close_expire_comment'	=> '<span class="xg1">Optional date format :2010-12-31 10:50</span>',//'<span class="xg1">选填日期格式：2010-12-01 10:50</span>',
	'admin_delthread_confirm'	=> 'Czy na pewno chcesz usunąć ten temat??',//'您确认要删除？',
	'topicadmin_mobile_mod'		=> 'Topic action mobile version',//'手机版主题操作',
	'admin_banpost_confirm'		=> 'Czy na pewno chcesz zablokować ten post?',//'您要进行屏蔽操作',
	'admin_delpost_confirm'		=> 'Czy na pewno chcesz usunąć ten post?',//'您确定要删除此回复？',
	'admin_warn_confirm'		=> 'Alerts the author that you want to warn',//'您要进行警告操作',
	'attach_nopermission_login'	=> '<a href="member.php?mod=logging&action=login">Zaloguj się</a>, aby móc pobierać lub przeglądać załączniki. Nie masz jeszcze konta? <a href="member.php?mod={$_G[setting][regname]}" title="Rejestracja">Zarejestruj się</a>',//'您需要<a href="member.php?mod=logging&action=login">登录</a>才可以下载或查看附件。没有帐号？<a href="member.php?mod={$_G[setting][regname]}" title="注册帐号">{$_G[setting][reglinkname]}</a>',
	'attachlist'			=> 'Lista załączników',//'附件列表',
	'ban_member'			=> 'Ban',//'禁止',
	'digest'			=> '<span class="xi1">Wykop</span>',//'<span class="xi1">精华</span>',
	'forum_views'			=> 'Wyświetleń',//'看',
	'send_pm'			=> 'Wyślij PW',//'发消息',
	'thread_show_all'		=> 'Zobacz wszystko',//'看全部',
	'thread_show_author'		=> 'Wyświetl profil',//'只看他',
	'activity_mod'			=> 'Please use the non-mobile version for manage your activities',//'请您使用非手机版管理活动',
	'poll_msg_allwvote_user'	=> 'You need to <a href="member.php?mod=logging&action=login">Login</a> for vote the poll',//'您需要<a href="member.php?mod=logging&action=login">登录</a>之后方能进行投票',
	'resolved'			=> 'Resolved',//'已解决',
	'unresolved'			=> 'Unresolved',//'未解决',
	'trade_mod'			=> 'Please use the non-mobile version for manage product',//'请您使用非手机版管理商品',
	'my_favorites_thread'		=> 'Moje ulubione tematy',//'我收藏的帖子',
	'return_forum'			=> 'Powrót do forum',//'返回论坛',
	'title_memcp_favorite'		=> 'Ulubione',//'收藏',
	'back'				=> 'Powrót',//'返回',
	'chatpm'			=> 'Wiadomość grupowa',//'群聊',
	'chatpm_author'			=> 'Autor',//'发起者',
	'pm_totail'			=> 'PW',//'交谈',
	'pm_with'			=> 'z',//'与',
	'user_mobile_pm_error'		=> 'Mobilne wiadomości nie wspierają wszystkich możliwych funkcji. Powróć do <a href="home.php?mod=space&do=pm&filter=privatepm">Moje wiadomości</a>.',//'手机版不支持复杂短消息操作，请返回<a href="home.php?mod=space&do=pm&filter=privatepm">我的短消息</a>',
	'basic_information'		=> 'Informacje podstawowe',//'基本资料',
	'favorite_description_default'	=> 'Mobilne ulubione',//'手机收藏',
	'favorite_forum_confirm'	=> 'Dodaj to forum:',//'收藏此版块: ',
	'favorite_thread_confirm'	=> 'Dodaj ten temat:',//'收藏此主题: ',
	'user_mobile_pm_comment'	=> 'After the messages sent you will returned to previous page',//'短消息发出后将跳回上一页',
	'reset'				=> 'Reset',//'重填',
	'reg_username'			=> 'User name length must be in a range of 3-15 characters',//'用户名必须为大于3位小于15位',
);

